#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "npm trusted publishing for @readyrun/readyrun"

# ── Stage 1: npm CLI login ────────────────────────────────────────────────
stage "npm: who are you?"
say "Publishing and org creation need your npm account (MichaelBuss)."
if command -v npm >/dev/null 2>&1 && WHOAMI=$(npm whoami 2>/dev/null); then
  say "Logged in to npm as: $WHOAMI"
  if ! confirm "Is $WHOAMI the account that should own the readyrun org?"; then
    step "Run: npm logout  (then continue; the next check offers login)"
    pause "Press Enter when ready to continue"
  fi
fi
if ! command -v npm >/dev/null 2>&1; then
  warn "npm not found; install Node >= 24 first (https://nodejs.org)"
  pause "Press Enter once npm is available"
fi
if ! WHOAMI=$(npm whoami 2>/dev/null); then
  say "Not logged in. This opens a browser; complete the login there."
  pause "Press Enter to run: npm login"
  npm login
  WHOAMI=$(npm whoami)
  say "Logged in as: $WHOAMI"
fi

# ── Stage 2: create the readyrun org ──────────────────────────────────────
stage "npmjs.com: create the readyrun org"
say "The @readyrun scope needs an npm org named readyrun (free plan is fine:"
say "it allows unlimited public packages)."
open_url "https://www.npmjs.com/org/create"
step "Org name: readyrun"
note "  If the name is taken, STOP: the package name @readyrun/readyrun"
note "  depends on it, and we'd need a different name on npm entirely."
step "Pick the free plan and create the org."
pause "Press Enter once the org exists"

# ── Stage 3: bootstrap-publish 0.1.5 ──────────────────────────────────────
stage "npm: bootstrap-publish @readyrun/readyrun@0.1.5"
say "Trusted publishing is configured on a package's settings page, so the"
say "package must exist first. One manual publish claims the name."
VERSION=$(node -p "require('./package.json').version")
REPO=$(node -p "require('./package.json').repository.url")
say "Publishing from this checkout: version $VERSION, repository $REPO"
note "  Tarball contents (files: src, LICENSE, README.md):"
npm pack --dry-run 2>&1 | grep "npm notice" | tail -20 || true
if confirm "Publish @readyrun/readyrun@$VERSION to npm for real?"; then
  npm publish --access public
  say "Published. The package page now exists, and the name is yours."
else
  warn "Skipped. Stages 4-6 can't work until the package exists; re-run later."
  finish
  exit 0
fi

# ── Stage 4: configure the trusted publisher ──────────────────────────────
stage "npmjs.com: configure the trusted publisher"
say "This wires CI publishes to this exact repo + workflow, with no tokens."
open_url "https://www.npmjs.com/package/@readyrun/readyrun/settings"
step "Open the 'Trusted publishing' (or 'Trusted Publisher') section."
step "Click 'Add trusted publisher' and choose GitHub Actions."
step "Organization or user: MichaelBuss"
step "Repository:            readyrun"
step "Workflow filename:     publish.yml     (just the filename, case-sensitive)"
step "Environment name:      leave empty"
warn "Tick 'Allow npm publish' — since Sep 2026 new configs default to"
warn "stage-only, which would force a human 2FA approval on every release."
step "Save."
note "  npm does not validate the config on save; mistakes surface at publish"
note "  time. Double-check every field. First publish must happen within 2"
note "  days or the config expires."
pause "Press Enter once the trusted publisher is saved"

# ── Stage 5: lock publishing access (optional, recommended) ───────────────
stage "npmjs.com: disallow tokens (optional hardening)"
say "With trusted publishing in place, traditional tokens are the weaker"
say "path. Disabling them doesn't affect trusted publishing."
if confirm "Set 'Require two-factor authentication and disallow tokens' now?"; then
  step "On the same settings page, open 'Publishing access'."
  step "Select: Require two-factor authentication and disallow tokens."
  step "Click: Update Package Settings."
  pause "Press Enter when saved"
else
  note "Skipped. You can do this any time: package Settings → Publishing access."
fi

# ── Stage 6: go live ──────────────────────────────────────────────────────
stage "Ship the release that proves the whole chain"
say "Now the end-to-end test: two merges, then watch one workflow run."
step "1. Merge PR #178 (the release-system PR). Its changeset opens the"
step "   Version Packages PR automatically (bumps to 0.2.0, writes CHANGELOG.md)."
open_url "https://github.com/MichaelBuss/readyrun/pull/178"
step "2. Merge that Version Packages PR."
step "3. Watch the 'Release' workflow: it publishes npm (OIDC) and JSR, tags"
step "   v0.2.0, and creates the GitHub Release."
open_url "https://github.com/MichaelBuss/readyrun/actions/workflows/publish.yml"
note "  If npm fails with setup instructions instead of publishing, compare the"
note "  error against stage 4's fields (workflow filename and repository are"
note "  case-sensitive) and re-run the failed workflow from the Actions tab."
note "  The 2-day clock on the trusted-publisher config started in stage 4."
pause "Press Enter to finish"

finish
